[build]
builder = "nixpacks"
buildCommand = "npx install -g pnpm && pnpm install && npm run build"
#dockerfilePath = "Dockerfile.backend"



[deploy]
#FIXME: remove
startCommand = "npx prisma migrate deploy & sleep 2 && npx pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 200
restartPolicyType = "on_failure"
numReplicas = 1
restartPolicyMaxRetries = 1


#https://docs.railway.app/deploy/config-as-code
